export const editorialBoardData = [
    {
        id: 1,
        name: "Dr. Vijayalaxmi Biradar",
        designation: "Professor & Director IQAC",
        email: "dr.vijayalaxmi@kalingauniversity.ac.in",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/vijaylaxmi.png",
        affiliation: "Kalinga University, Naya Raipur, CG",
        irins: "278433",
        scopus: "57185507000",
        expertise: `Dr. Vijayalaxmi Biradar stands out as a visionary leader & as a highly accomplished academician in the field of Electronics and Communication Engineering, currently serving as Professor and Director of IQAC at Kalinga University, Raipur. With a Ph.D. from GITAM University and over two decades of experience, she has significantly contributed to education, research, and institutional quality enhancement. A Senior IEEE Member, she holds prestigious roles including Secretary and Chairperson of IEEE WIE AG Madhya Pradesh Section and Program Co-Chair of the IEEE Women in Engineering International Leadership Conference 2025 in San Jose, USA. Dr. Biradar has authored over 60 above research papers, guided multiple Ph.D. students, published 7 patents, and secured research and consultancy projects worth over ₹1 crore. Her accolades include the 2024 IEEE WIE Inspiring Member Award (Honorable Mention), R10 WIE Outstanding Professional Volunteer Award 2024, and “Women Leadership in STEM” recognition by BIRAC and WomenLift Health. As an IEEE STEM Champion and NAAC Assessor for the Government of India, she has mentored several HEIs to achieve NBA/NAAC accreditations and A+ grades, while actively promoting STEM education, innovation, and women empowerment across India and globally. She is also recognized for her expertise in establishing Centers of Excellence (CoEs) and advancing STEM education through innovative programs, collaborations, and capacity-building initiatives that foster technological and educational development.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 2,
        name: "Prof. (Dr.) G.S. Tomar",
        designation: "Director",
        email: "gstomar@ieee.org",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/gs-tomer.png",
        affiliation: "Rajkiya Engineering College, Sonbhadra, UP",
        irins: "583778",
        scopus: "16176798100",
        expertise: `G.S. Tomar sir is IEEE Senior Member, Fellow IETE and IE (I) member ACM (USA), CSI and ISTE, Chairman, IETE Gwalior and IEEE MP Subsection. Dr. Tomar is an accomplished academician and researcher with extensive leadership experience in premier engineering institutions. He holds a Post-Doctoral Fellowship in Computer Engineering from the University of Kent, UK, and has served as faculty and director at multiple reputed institutes, including University of Kent, University of West Indies, Birla Institute Bhimtal, and others. With a 17-year tenure in the Indian Air Force, Dr. Tomar transitioned to academia in 2001 and has since been deeply involved in IEEE activities, organizing over 10 international conferences globally. He is a Visiting Professor at several reputed universities, including Hannam University, Korea, and Thapar University, India. Dr. Tomar has received the International Pluto Award for Academic Excellence (2009) and has been listed among the top 100 academicians worldwide. He is chief editor of five international journals, has published over 100 research papers, and authored five books, including two Springer Verlag publications. His research expertise lies in Air Interface and Advanced Communication Networks, with a strong focus on consultancy and innovation in these domains.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 3,
        name: "Prof. (Dr.) Celia Shahnaz",
        designation: "Professor, Department of EEE",
        email: "celia@eee.buet.ac.bd",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/(Dr.)-Celia-Shahnaz.png",
        affiliation: "Bangladesh university of Engineering and Technology (BUET), Bangladesh",
        irins: "NA",
        scopus: "13609620100",
        expertise: `Celia Shahnaz, SMIEEE, Fellow IEB, received Ph.D. degree from Concordia University, Canada and is currently a professor at, Department of EEE, BUET, Bangladesh since 2015. She was the winner of Canadian Common Scholarship for pursuing her Ph.D study in Canada and recipient of Bangladesh Academy of Science Gold Medal for her contributions in science and technology. The World Academy of Science (TWAS) members have elected her as a Fellow of TWAS for the advancement of science in developing countries, effective 1 January 2023. Recently, her nomination has been approved and she has been inducted into IEEE-Eta Kappa Nu as a Professional Member into the Eta Chapter of the Board of Governors. She has been elected as 2022 IEEE WIE Committee Chair-Elect and she is serving as the 2023-2024 IEEE WIE Committee Chair. She has been appointed as 2024, Division V Representative, IEEE TAB Award and Recognition Committee , 2024 Member, IEEE Fourier Award for Signal Processing Committee , 2024 IEEE Computer society Awards Chair, 2024 Member, IEEE CS Election Committee, 2024 Member, IEEE Fourier Award for Signal Processing Committee, 2022-23 Member, IEEE New Initiative Committee, 2021-24 Member, IEEE History Committee, Liaison between IEEE History Committee and IEEE WIE, 2023 Corresponding member, IEEE BOD Ad-Hoc: Coordinating IEEE’s Response to Multimedia-Based Digital Reality Technologies, 2023 Member, the future of the IEEE WIE ILC Adhoc. She has served as 2021-22 Chair, IEEE SPS Women in Signal Processing, 2021-22 Liaison between IEEE SPS and IEEE WIE, 2021-22 Member, IEEE Educational Activities Board Faculty Resource Committee, 2022 Member, IEEE WIE Strategic planning Committee, 2021 Chair, IEEE WIE History Subcommittee, 2020-21 Member, IEEE WIE Senior Member Elevation Drive and 2019-2022 Member, IEEE WIE WePower Subcommittee. She has served as an Editorial board member, IET Signal Processing From 2018 to date. She is the immediate past Chair, IEEE Bangladesh Section, Co-founder & Chair, IEEE EMBS, IAS, RAS, SSIT Bangladesh Chapters, Co-founder & Vice-Chair, IEEE SPS Bangladesh Chapter, Founder and Advisor, WIE AG, and founder and Chair of SIGHT group FLASH, IEEE Bangladesh Section. She is the recipient of the 2021 IEEE MGA Achievement Award, 2021 Inspiring Women in Academia Award from Bangladesh brand forum, 2019 R10 Humanitarian Activities Outstanding Volunteer Award, 2016 MGA Leadership Award 2015 WIE Inspiring Member Award, 2013 R10 WIE Professional Volunteer Award. She has more than 24 years of experience (24 years as an IEEE volunteer) in leading impactful Technical, Professional, Educational, Industrial, Women Empowerment, Humanitarian Technology, Power and Energy-related Projects at national/international levels.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 4,
        name: "Dr. Tanushree Chatterjee",
        designation: "Dean & HOD, Biotechnology",
        email: "hod.bio@rit.edu.in",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Dr.+Tanushree+Chatterjee.png",
        affiliation: "RITEE, Raipur, CG",
        irins: "129842",
        scopus: "57904264900",
        expertise: `Dr. Tanushree Chatterjee is a distinguished leader in biotechnology with over 30 years of post-Ph.D. experience. Currently serving as Dean and Head of the Department of Biotechnology at Raipur Institute of Technology (RITEE), she holds a Ph.D. from the University of Allahabad and completed her postdoctoral fellowship at CSIR, New Delhi. Dr. Chatterjee has made significant contributions in biotechnology, environmental science, bioinformatics, and biomedical engineering, authoring over 70 research papers and guiding multiple Ph.D. students.\n\nShe has worked as a consultant for three mining sites of GMDC in Gujarat and collaborated with Germany’s Rostock University and FAU University. Additionally, she has successfully led numerous research projects funded by CSIR, DST, MODROB, MOEF, and TEQIP, serving as both principal and co-principal investigator. Her extensive academic, research, and consultancy experience highlights her commitment to advancing biotechnology education and sustainable development. She is also a recipient of Global Awards for Excellence in Research in 2019 and 2020.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 5,
        name: "Prof. (Dr.) Zuhaina Zakaria",
        designation: "Professor",
        email: "zuhainaz@uitm.edu.my",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Zuhaina+Zakaria.png",
        affiliation: "Universiti Teknologi MARA, Malaysia",
        irins: "NA",
        scopus: "0000-0003-0281-1993",
        expertise: `Prof. Ir. Dr. Zuhaina Zakaria is a distinguished academic and engineer at Universiti Teknologi MARA (UiTM), Malaysia, known for her expertise in Electrical Engineering, significant roles like Dean of Institute Graduate Studies (IPSis), and contributions to power systems research, particularly focusing on photovoltaic integration & load profiling, holding multiple professional engineering certifications and driving UiTM's postgraduate development.\n\nKey Highlights:\nRole at UiTM: Formerly the Dean of the Institute of Graduate Studies (IPSis) at UiTM, managing postgraduate programs. Academic Background: Holds a Bachelor's in Electrical Engineering from UiTM. Expertise: Specializes in Electrical Engineering, focusing on power systems, fuzzy logic applications, and photovoltaic (SPV) integration into power grids. Professional Affiliations: A registered Professional Engineer (PE), Member of the Institution of Engineers Malaysia (MIEM), Chartered Engineer (CEng), and holds several international engineering credentials (APEC Engineer, ASEAN Eng.). Research Focus: Develops advanced algorithms (like FIPA in Python) to handle uncertainties in renewable energy (SPV) and improve grid stability and planning. In essence, she's a highly qualified engineer and educator deeply involved in advancing research and postgraduate education at Malaysia's leading technology university.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 6,
        name: "Dr Thittaporn Ganokratanaa",
        designation: "Professor, Department of Mathematics",
        email: "thittaporn.gan@kmutt.ac.th",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Dr+Thittaporn+Ganokratanaa.png",
        affiliation: "King Mongkut's University of Technology Thonburi, Bangkok",
        irins: "NA",
        scopus: "0000-0003-0281-1993",
        expertise: `Thittaporn Ganokratanaa is a University Lecturer in Applied Computer Science Programme at King Mongkut’s University of Technology Thonburi, Bangkok, Thailand. She is the IEEE Region 10 Student Activities Committee (IEEE R10 SAC) and IEEE Member and Geographic Activities (MGA) SAC Awards Committee. Her research interests include anomaly detection, image and video analysis, and human-computer interaction.\n\nStrategic Research Themes\n• Assistive Technology for the Aged & Disabled & Rehabilitation (Smart Healthcare)\n• Creative and Learning Society (Strategic Research Themes)\n• Digital Transformation (Strategic Research Themes)\n• Information Technology (Digital Transformation)\n• Intelligent Transportation System (Sustainable Mobility)\n• Robotics & Automation (Medical Diagnostics)\n• Smart Healthcare (Strategic Research Themes)`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 7,
        name: "Dr Mohammad Nasir",
        designation: "Professor & University Librarian",
        email: "mohammad.nasir@kalingauniversity.ac.in",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Dr+Mohammad+Nasir+.png",
        affiliation: "Kalinga University, Naya Raipur, Chhattisgarh, India",
        irins: "532843",
        scopus: "59929497200",
        orcid: "0009-0006-1823-2717",
        expertise: `Prof. Mohammad Nasir is a senior library & Information science academician at Kalinga University (Naya Raipur, Chhattisgarh), where he serves as Professor and University Librarian (HoD, Dept. of Library & Information Science). He holds a Ph.D. in Library Science and has over 17 years of experience in academic librarianship. His research interests include digital resource management, library automation, information literacy and scholarly communication reflecting his dedication to enhancing access to knowledge and research support\n\nDr. Nasir has authored several textbooks, and research works in library science. Notable books include: Information technology in Library and Information Science: concepts, applications and Innovations (2025), Research Methods in Library and Information Science: a systematic approach (2025), Information Media and Library Science (2012), Library Classification and Automation, Cataloguing and Indexing in Library Science and Dictionary of Terms in Library and Information Science (2024). He has also published numerous articles and conference papers on topics like bibliometric study, digital libraries, database management, and user services in academic libraries.\n\nDr. Nasir’s work emphasizes modern, user-friendly library systems. For example, he co-developed a kiosk-based OPAC (Online Public Access Catalog) system with touchscreen and voice-search features to improve user access and engagement. These technology-enabled innovations illustrate his focus on integrating digital tools into library operations.\n\nContributions and Recognition\nProf. Nasir is active in professional forums presenting at national and international seminars and workshops and has helped establish and modernize academic libraries. His leadership in librarianship has been acknowledged by professional bodies (he received an “Innovative Librarian” award in 2020) and he continues to pioneer technology-driven library services. Overall, his career combines academic administration, research, and hands-on library development to advance information services and education in India`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 8,
        name: "Dr. Teena Singh",
        designation: "Professor & Registrar",
        email: "teena.singh@ndimdelhi.org",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Dr.+Teena+Singh.png",
        affiliation: "New Delhi Institute of Management (NDIM), New Delhi",
        irins: "445874",
        orcid: "0000-0002-5717-6408",
        scopus: "NA",
        expertise: `Dr. Teena Singh is an experienced educationist and HR professional with over 22 years of expertise across corporate, academic, and strategic consultancy roles. Currently serving as Professor and Registrar at the New Delhi Institute of Management (NDIM) since 2009, she specializes in Human Resource Management and General Management. Her contributions include organizing numerous conferences, MDPs, and summits, along with publishing research on student engagement, employee engagement, and psychological well-being. She is a certified POSH trainer and serves as an external member of the POSH Committee at CDAC, Ministry of Electronics and IT. Dr. Singh is also an active member of the CII Northern Region HR-IR Committee and the Academic Council of the NHRD Network, Delhi NCR Chapter. An accomplished author, she has written a book on People Management in the 21st Century, published by McGraw Hill.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    },
    {
        id: 9,
        name: "Dr. Chanakya Kumar Jha",
        designation: "Director Planning",
        email: "director@wbspune.org",
        img: "https://s3.ap-south-1.amazonaws.com/cdn.kalingauniversity.ac.in/departments/international-journal-of-research-and-studies/Dr.+Chanakya+Kumar+Jha.png",
        affiliation: "Siddhant Group of Institutions (SGI) Pune, Maharashtra",
        irins: "452831",
        scopus: "58341981700",
        expertise: `Dr. Chanakya Kumar Jha, Ph.D., is a distinguished academic and administrator with extensive leadership experience in higher education, research, and professional organizations. Currently serving as Director (Planning) at Siddhant Group of Institutions, Pune, and Managing Director at Western Business School, he has held various key positions, including Secretary of the Federation of World Academicians (2021–2022) and Vice Chair of multiple IEEE India Council committees.\n\nWith editorial experience as Chief Editor of the Asian Society for Scientific Research and Associate Editor for IEEE Access, Dr. Jha contributes significantly to academic publishing. His research background in Wireless Communication, coupled with active roles in IEEE’s Bombay Section and Region 10, underscores a strong commitment to advancing scientific knowledge and editorial excellence in engineering and management domains.`,
        variant: "editorial",
        exploreLinkText: "View Profile"
    }
];
